//C
INSERT INTO POST VALUES (3,'Czesc','DELETED')

//R
SELECT TEXT, ID FROM POST WHERE ID>1

//U
UPDATE POST SET TEXT='HELLO' WHERE ID=3

//D
DELETE FROM POST WHERE ID=1

//List
SELECT TEXT, ID FROM POST WHERE SCOPE='DELETED'