//HOMEWORK 

CREATE TABLE INVOICE(ID INT PRIMARY KEY AUTO_INCREMENT, NUMBER VARCHAR(255));

 //C
INSERT INTO INVOICE (NUMBER) VALUES('Invoice1');
INSERT INTO INVOICE (NUMBER) VALUES('Invoice2');
INSERT INTO INVOICE (NUMBER) VALUES('Invoice3');
INSERT INTO INVOICE (NUMBER) VALUES('Invoice4');
INSERT INTO INVOICE (NUMBER) VALUES('Invoice5');

//R
SELECT * FROM INVOICE ORDER BY ID;

SELECT * FROM INVOICE WHERE ID=2;

//U
UPDATE INVOICE SET NUMBER='Invoice01' WHERE ID=1;

//D
DELETE FROM INOVICE WHERE ID=2;

//LIST
SELECT * FROM INVOICE WHERE NUMBER LIKE '%3' AND (ID=1 or ID=2 or ID=3);
SELECT * FROM INVOICE WHERE NUMBER LIKE '%3' AND ID IN (1,2,4);